export { drawer } from '_/objects/drawer'
export { inn_bed } from '_/objects/inn/inn_bed'
export { inn_door } from '_/objects/inn/inn_door'
export { mirror } from '_/objects/mirror'
export { envelope } from '_/objects/envelope'